// Pentium Constructions — accurate content library sourced from pentiumconstructions.in
// Real images served from the live site. Unpublished fields => null ("available on request").

const B = "https://www.pentiumconstructions.in/admin/storage/app/public";
const g = (p) => `${B}/${p}`;

export const BRAND = {
  name: "Pentium Constructions",
  legal: "Pentium Construction Pvt. Ltd.",
  since: 1994,
  tagline: "Responsible Building. Unmatched Craft.",
  sub: "Premium Living, Kerala",
  phone: "+91 9544 141 000",
  phoneHref: "tel:+919544141000",
  phoneUAE: "+971 56 724 1497",
  whatsapp: "https://wa.me/919544141000",
  salesEmail: "sales@pentiumconstructions.in",
  adminEmail: "admin@pentiumconstructions.in",
  emailHref: "mailto:sales@pentiumconstructions.in",
  adminPhone: "0495 - 2768946",
  offices: [
    { label: "Admin Office", text: "2nd Floor, Mananchira Tower, A.G. Road, Kozhikode, Kerala" },
    { label: "Branch Office", text: "1st Floor, Lucia Tower, Bypass Jn., Perinthalmanna - 679 322" },
    { label: "Regd. Office", text: "No. 84/44, 2nd Floor, 2nd Main Road, Vinayaka Circle, Vyalikaval, Bangalore - 560003" },
  ],
  address: "2nd Floor, Mananchira Tower, A.G. Road, Kozhikode, Kerala",
};

export const STATS = [
  { value: 2000, suffix: "+", label: "Happy Clients" },
  { value: 23, suffix: "+", label: "Projects Built" },
  { value: 3, suffix: "", label: "Active Projects" },
  { value: 1994, suffix: "", label: "Established", noPlus: true },
];

export const HERO_IMG = g("project/06-08-26-06-32-Harmony-Heights.jpg");

const AR = (title, text) => ({ title, text });

export const PROJECTS = [
  {
    key: "project_harmony",
    name: "Harmony Heights",
    slug: "harmony-heights",
    type: "Luxury Apartments · 2 & 3 BHK",
    location: "Perinthalmanna, Malappuram",
    status: "ongoing",
    badge: "Ongoing · 45%",
    rera: "K-RERA/PRJ/MPM/232/2024",
    config: "2 & 3 BHK",
    floors: "18 Floors",
    units: "60 Apartments",
    areaRange: "1,494 – 2,133 sq ft",
    land: "2,396.50 sq m",
    started: "1 Jan 2025",
    completion: "31 Dec 2028",
    image: g("project/06-08-26-06-32-Harmony-Heights.jpg"),
    videoId: "h00HlgYdVKE",
    overview: "Ultra-luxury 2 & 3 BHK apartments across 18 floors in Perinthalmanna, where urban luxury meets environmental mindfulness.",
    vision: "Harmony Heights — a name that encapsulates our commitment to durable happiness. Extra-spacious 2 & 3 BHK apartments with large balconies and windows for ample natural light and ventilation, plus dedicated meditation and yoga areas. An air-conditioned indoor games area, rooftop party area with barbecue corner, swimming pool, well-equipped gym, air-conditioned co-working space and EV charging points make life here extraordinarily convenient.",
    amenitiesCount: 44,
    amenities: [
      "Automated gate", "24-hour security", "Biometric control at common entrance", "CCTV surveillance",
      "Drop-off area", "High-speed elevators – 3 nos.", "Multi-level basement car parking", "Guest car parking",
      "Bicycle parking", "Two-wheeler parking", "Wheelchair-friendly ramps", "Swimming pool with kids' pool",
      "Children's play pen area", "Multi-purpose game zone", "AC indoor games (carrom, chess, TT, billiards)",
      "Fitness centre", "AC zumba / aerobics room", "Rooftop meditation / yoga space", "AC multipurpose hall",
      "Terrace-top open party area", "Barbecue corner", "Senior citizen area", "Guest lounge", "Study / library room",
      "Co-working space", "High-speed internet in lobby", "Intercom facility", "Home care office", "Guest drivers room",
      "Janitor room", "Provision for stationery shop", "Provision for beauty parlour", "Well & KWA water",
      "Centralized gas line provision", "Cable TV provision", "EV charging provision", "Generator power backup",
      "Roof-top solar lighting", "Landscaped area", "LED water fountain", "Rainwater harvesting",
      "Sewage treatment plant", "Bio-waste plant", "Ironing area",
    ],
    specs: [
      AR("Flooring", "High-quality vitrified / rectified tiles for living, dining, bedrooms, kitchen, lobby, staircase & common areas. Brands: RAK, Kajaria, AGL, Nitco, Somany, Simpolo or equivalent."),
      AR("Kitchen", "High-quality tile flooring; openings for hood & exhaust fan; electric points for appliances; water inlet/outlet for washing machine. Tile: RAK, Kajaria, AGL, NITCO, Somany, Simpolo or equivalent."),
      AR("Toilet", "Anti-skid tiled flooring, glazed-tile dado, wall-mounted closets & washbasin, premium CP fittings, hot & cold mixer with shower. Fittings & sanitaryware: Grohe, Jaquar, CERA."),
      AR("Electrical", "Three-phase concealed wiring with adequate light/fan points, 6A & 16A plug points, ELCB/MCB, independent meters, modular switches, cable-TV & telephone in living, intercom in master bedroom. Brands: Legrand, Finolex, Polycab, Havells or equivalent."),
      AR("Doors, Windows & Handrails", "Superior teak wood entrance door & frame; pre-hung molded laminated/flush inner shutters; aqua-coated toilet shutters; UPVC sliding balcony doors; powder-coated aluminium windows with MS grills. Glass: Saint Gobain."),
      AR("Painting", "Branded putty (two coats), one coat primer, two coats emulsion for interiors; all-weather coat for exteriors; enamel for grills & handrails. Brands: Berger, Jotun, Birla, Nerolac, Asian Paints or equivalent."),
      AR("Elevators", "Three high-speed elevators. Brands: Johnson / Kone / Otis or equivalent."),
      AR("Generators", "Generator backup up to 900 W per apartment. Brands: Cummins, Kirloskar or equivalent."),
      AR("Water Supply", "Excellent ground water supported by KWA; two-pipe system for domestic & drinking water."),
      AR("Car Parking", "Multi-level basement parking plus ground & first floor; EV charging at common parking area."),
      AR("Security", "CCTV surveillance in common areas. Brand: Hikvision or equivalent."),
      AR("Fire Safety", "Fire-fighting equipment as per Kerala building rules, sprinklers, smoke detectors & extinguishers."),
      AR("Waste Disposal", "Sewage treatment plant per pollution-control norms; biogas plant for waste disposal."),
      AR("Finance", "Approved by major financial institutions for easy long-term loans."),
    ],
    blueprints: [
      { label: "Basement", url: g("floor/04-08-26-12-07-HH-BASEMENT-FLOOR.webp") },
      { label: "Ground" }, { label: "First" }, { label: "Typical" },
      { label: "Type A" }, { label: "Type B" }, { label: "Type C" }, { label: "Type D" },
    ],
    gallery: [
      g("project/06-08-26-06-32-Harmony-Heights.jpg"),
      g("project_gallery/04-08-26-11-57-hh-glry-img-new11.webp"),
      g("project_gallery/04-08-26-11-16-hh-glry-img-new2.webp"),
      g("project_gallery/04-08-26-11-34-hh-glry-img-new3.webp"),
      g("project_gallery/04-08-26-11-51-hh-glry-img-new1.webp"),
      g("project_gallery/04-08-26-11-06-hh-glry-img-new4.webp"),
      g("project_gallery/04-08-26-11-17-hh-glry-img-new5.webp"),
      g("project_gallery/04-08-26-11-28-hh-glry-img-new6.webp"),
      g("project_gallery/04-08-26-11-40-hh-glry-img-new7.webp"),
      g("project_gallery/04-08-26-11-52-hh-glry-img-new8.webp"),
      g("project_gallery/04-08-26-11-04-hh-glry-img-new9.webp"),
      g("project_gallery/04-08-26-11-19-hh-glry-img-new10.webp"),
    ],
  },
  {
    key: "project_tranquil",
    name: "Tranquil Vertical Home",
    slug: "tranquil-vertical-home",
    type: "Luxury Apartments · 2 & 3 BHK",
    location: "Nellikavu, Eranhipalam, Calicut",
    status: "ongoing",
    badge: "Ongoing · Nearing completion",
    rera: "K-RERA/PRJ/KKD/063/2021",
    config: "2 & 3 BHK",
    floors: "Ground + 4 Floors",
    units: "28 Homes",
    areaRange: "1,314 – 1,863 sq ft",
    land: null,
    started: null,
    completion: "Nearing completion",
    image: g("project/06-08-26-05-14-Tranquil-Vertical-Home.jpg"),
    videoId: "oC7IjQKej3A",
    overview: "Premium 2 & 3 BHK apartments in the serene neighbourhood of Nellikavu near Eranhipalam — luxury meets tranquility in the heart of Calicut.",
    vision: "Nestled in the serene neighbourhood of Nellikavu near Eranhipalam, Pentium Tranquil offers the chance to disconnect from the city's hustle while enjoying the privileges of city living. 28 meticulously designed 2 & 3 BHK homes over Ground + 4 floors, each crafted for a seamless blend of elegance and comfort. Currently nearing completion — an opportunity to personalise and customise your future home.",
    amenitiesCount: 18,
    amenities: [
      "24-hour security", "CCTV surveillance", "Passenger lifts (2 nos.)", "Visitor car parking",
      "Wheelchair-friendly ramps", "Outdoor children's play area", "Fitness centre", "Terrace-top open party area",
      "Intercom facility", "Home care office", "Centralized gas line provision", "Generator power backup",
      "Roof-top solar lighting", "LED lighting in common areas", "Landscaped area", "Rainwater harvesting",
      "Sewage treatment plant", "Biogas plant",
    ],
    specs: [
      AR("Wall & Flooring", "60 x 60 vitrified tiles in lobby, common areas and rooms."),
      AR("Painting", "Putty finish with emulsion for interior walls, water-proof exterior walls, enamel for inner doors, handrails & grills."),
      AR("Windows", "Fully glazed / powder-coated aluminium sliding shutters with MS grills."),
      AR("Kids Play Area", "A beautiful, nature-friendly play area that keeps children happy and energetic while staying safe."),
      AR("Gym", "A premium fitness station with proper equipment for a wellness-inspired lifestyle."),
      AR("Doors", "Ultra-modern, weather-resistant and durable doors combining safety and aesthetics."),
      AR("Toilet", "Anti-skid tiled flooring, glazed-tile dado up to 210 cm, provision for wall-mounted geyser & exhaust fan, hot & cold mixer taps & showers."),
      AR("Electrical", "Three-phase wiring with single-phase connection, concealed copper wiring, adequate points controlled by ELCB/MCB."),
      AR("Sanitary Fixtures", "Western-style water closets in bedroom toilets; wash basins in common area."),
      AR("Water Supply", "Groundwater source supported by KWA."),
      AR("Car Parking", "Ample car parking at ground floor."),
      AR("Finance", "Approved by major banks for easy long-term loans."),
    ],
    blueprints: [
      { label: "Ground", url: g("floor/04-08-26-03-31-ground.webp") },
      { label: "Type A" }, { label: "Type B" }, { label: "Type C" }, { label: "Type D" },
      { label: "Type E" }, { label: "Type F" }, { label: "Type G" }, { label: "Typical" },
    ],
    gallery: [g("project/06-08-26-05-14-Tranquil-Vertical-Home.jpg")],
  },
  {
    key: "project_spring_green",
    name: "Spring Green Villas",
    slug: "spring-green-villas",
    type: "Luxury Villas · 3, 4 & 5 BHK",
    location: "Perinthalmanna, Malappuram",
    status: "ongoing",
    badge: "Ongoing",
    rera: "K-RERA/PRJ/MPM/172/2021",
    config: "3, 4 & 5 BHK",
    floors: null,
    units: "37 Units",
    areaRange: "1,296 – 2,604 sq ft",
    land: null,
    started: null,
    completion: null,
    image: g("project/06-08-26-05-40-Spring-Green-Villas.jpg"),
    videoId: "1996OhKZEr4",
    overview: "Premium 3, 4 & 5 BHK villas in Perinthalmanna, blending natural beauty, modern comfort and luxury for an exceptional living experience.",
    vision: "Pentium Spring Green Villas offer premium residences in Perinthalmanna, Malappuram — a gated community blending natural beauty, modern comfort and luxury living.",
    amenitiesCount: 20,
    amenities: [
      "Automated street lighting", "CCTV surveillance", "Gated community with compound wall & guard",
      "Wide internal roads", "Basement multi-level parking", "Swimming pool with kids' pool",
      "Outdoor children's play area", "Shuttle court", "AC indoor games", "Fitness centre",
      "AC multipurpose hall", "Intercom facility", "Drivers' room", "Well + KWA water", "Inverter wiring",
      "Generator power backup", "Landscaping & garden", "Rainwater harvesting", "Biogas plant", "Billiards",
    ],
    specs: null, // not exposed publicly -> "available on request"
    blueprintTabs: null,
    blueprint: null,
    gallery: [
      g("project/06-08-26-05-40-Spring-Green-Villas.jpg"),
      g("project_gallery/04-08-26-03-11-Spring-Green1.jpg"),
      g("project_gallery/04-08-26-03-37-Spring-Green2.jpg"),
      g("project_gallery/04-08-26-03-09-Spring-Green3.jpg"),
      g("project_gallery/04-08-26-03-42-Spring-Green4.jpg"),
    ],
  },
  // ---------- Completed ----------
  {
    key: "project_eternia",
    name: "Eternia Vertical Homes",
    slug: "eternia-vertical-homes",
    type: "Luxury Apartments · 2 & 3 BHK",
    location: "Karaparamba, Calicut",
    status: "completed",
    badge: "Completed",
    rera: "K-RERA/PRJ/259/2020",
    config: "2 & 3 BHK",
    floors: "14 Floors",
    units: "52 Units",
    areaRange: null,
    image: g("project/26-07-26-01-13-eternia-vertical-homes.jpg"),
    overview: "A masterpiece of urban luxury and environmental mindfulness — ultra-spacious 2 & 3 BHK residences across 14 thoughtfully designed floors.",
    vision: null, amenitiesCount: null, amenities: null, specs: null, blueprintTabs: null, blueprint: null,
    gallery: [g("project/26-07-26-01-13-eternia-vertical-homes.jpg")],
  },
  {
    key: "project_palm_grove",
    name: "Palm Grove",
    slug: "palm-grove",
    type: "Luxury Apartments",
    location: "Perinthalmanna, Malappuram",
    status: "completed",
    badge: "Completed",
    rera: null, config: null, floors: null, units: null, areaRange: null,
    image: g("project/06-08-26-11-04-Palm-Grove.jpg"),
    overview: "Palm Grove Luxury Apartments in Perinthalmanna, Malappuram.",
    vision: null, amenitiesCount: null, amenities: null, specs: null, blueprintTabs: null, blueprint: null,
    gallery: [g("project/06-08-26-11-04-Palm-Grove.jpg")],
  },
  {
    key: "project_aishwarya",
    name: "Aishwarya",
    slug: "aishwarya",
    type: "Luxury Apartments",
    location: "Calicut",
    status: "completed",
    badge: "Completed",
    rera: null, config: null, floors: null, units: null, areaRange: null,
    image: g("project/06-08-26-11-41-Aishwarya-Luxury.jpg"),
    overview: "Aishwarya Luxury Apartments in Calicut.",
    vision: null, amenitiesCount: null, amenities: null, specs: null, blueprintTabs: null, blueprint: null,
    gallery: [g("project/06-08-26-11-41-Aishwarya-Luxury.jpg")],
  },
  {
    key: "project_vrindavan",
    name: "Vrindavan",
    slug: "vrindavan",
    type: "Luxury Apartments",
    location: "Eranhipalam, Calicut",
    status: "completed",
    badge: "Completed",
    rera: null, config: null, floors: null, units: null, areaRange: null,
    image: g("project/06-08-26-11-01-Vrindavan.jpg"),
    overview: "Vrindavan Luxury Apartments in Eranhipalam, Calicut.",
    vision: null, amenitiesCount: null, amenities: null, specs: null, blueprintTabs: null, blueprint: null,
    gallery: [g("project/06-08-26-11-01-Vrindavan.jpg")],
  },
  {
    key: "project_civil_avenue",
    name: "Civil Avenue",
    slug: "civil-avenue",
    type: "Luxury Apartments",
    location: "Calicut",
    status: "completed",
    badge: "Completed",
    rera: null, config: null, floors: null, units: null, areaRange: null,
    image: g("project/06-08-26-11-20-Civil-Avenue.jpg"),
    overview: "Civil Avenue Luxury Apartments in Calicut.",
    vision: null, amenitiesCount: null, amenities: null, specs: null, blueprintTabs: null, blueprint: null,
    gallery: [g("project/06-08-26-11-20-Civil-Avenue.jpg")],
  },
  {
    key: "project_dream_city",
    name: "Dream City",
    slug: "dream-city",
    type: "Luxury Apartments",
    location: "Calicut",
    status: "completed",
    badge: "Completed",
    rera: null, config: null, floors: null, units: null, areaRange: null,
    image: g("project/06-08-26-11-39-Dream-City.jpg"),
    overview: "Dream City Luxury Apartments in Calicut.",
    vision: null, amenitiesCount: null, amenities: null, specs: null, blueprintTabs: null, blueprint: null,
    gallery: [g("project/06-08-26-11-39-Dream-City.jpg")],
  },
];

export const PROJECT_OPTIONS = PROJECTS.map((p) => p.name).concat(["General enquiry", "Not sure yet"]);

export const SERVICES = [
  { name: "Residential Construction", desc: "Custom homes, villas and apartments." },
  { name: "Commercial Construction", desc: "Offices, retail and mixed-use developments." },
  { name: "Industrial Construction", desc: "Factories, warehouses and manufacturing facilities." },
  { name: "Turnkey Projects", desc: "Concept, design, construction and handover by one team." },
  { name: "Renovation & Remodeling", desc: "Structural upgrades, interior renovation and restoration." },
  { name: "Project Management", desc: "Scheduling, budgeting, quality oversight and site supervision." },
  { name: "Interior & Finishing", desc: "Flooring, painting, electrical, plumbing and finishing." },
];

export const DIFFERENTIATORS = [
  "Precision engineering to IS 800 standards",
  "Passive ventilation & climate-resilient layouts",
  "Premium teakwood & granite finish palette",
  "RERA-certified, transparent documentation",
  "On-time delivery track record",
  "Support that continues after handover",
];

export const WHY_PILLARS = [
  { title: "Advanced Facilities", desc: "Modern technology and infrastructure across every build." },
  { title: "World-Class Amenities", desc: "Swimming pools, gyms, clubhouses and landscaped gardens." },
  { title: "Spacious Rooms", desc: "Airy, generously sized apartments and villas." },
];

export const QUALITY_STAGES = [
  { title: "Planning", desc: "Scope review, design validation, resource planning, early risk ID." },
  { title: "Procurement", desc: "Approved vendors, on-site material inspection, certified materials." },
  { title: "Construction", desc: "Skilled crews, active supervision, process & safety checks." },
  { title: "Inspection", desc: "Structural & finishing checks plus a final client walkthrough." },
  { title: "Handover", desc: "Final review, documentation, completion report & satisfaction check." },
];

export const GO_GREEN = [
  "Energy-efficient design", "Water conservation", "Responsible waste management",
  "Eco-friendly materials", "Lower carbon footprint", "Green landscaping",
];

export const CSR = [
  "Education support", "Community development", "Health & wellness outreach",
  "Environmental conservation", "Employee volunteering", "Disaster relief", "Skill development & youth programmes",
];

export const LEADERSHIP = [
  { name: "Mr. V. Gopinathan", role: "Chairman & Managing Director" },
  { name: "Mr. V. Sethu Madhavan", role: "Director" },
];

export const FAQS = [
  { q: "What kind of construction work do you handle?", a: "Residential, commercial, industrial, institutional and turnkey projects." },
  { q: "Can you help with design and planning?", a: "Yes — in-house architects and engineers handle planning, design and estimates." },
  { q: "How do you make sure the work holds up?", a: "Multi-stage inspections, standard materials and experienced site supervisors." },
  { q: "Do projects finish on time?", a: "Upfront planning, realistic scheduling and progress tracking keep us on time." },
  { q: "Is sustainability built in?", a: "Yes — energy-efficient design, less waste and lower-impact materials." },
  { q: "How do I get a quote?", a: "Contact us via form, email or phone for a consultation and tailored quotation." },
  { q: "Do you take on renovation work?", a: "Yes — renovation, remodelling, structural strengthening and modernisation." },
  { q: "What sets Pentium apart?", a: "Straightforward communication, consistent quality and every project treated as important." },
];
